"""Evidence for the handbook's four forecast traps, one check per "Detection and fix" item.

Usage:  python src/audit_traps.py      (after clean.py and forecast.py)
Writes: outputs/figures/*.png and outputs/trap_audit.md
"""
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.dates as mdates  # noqa: E402
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

import clean  # noqa: E402
from features import CALENDAR_FEATURES, PAST_FEATURES, SPIKE_FEATURES, build_rows, load_daily, load_weather  # noqa: E402

sys.stdout.reconfigure(encoding="utf-8")  # Windows consoles default to cp1252
ROOT = Path(__file__).resolve().parents[1]
FIG = ROOT / "outputs" / "figures"
HAZ = 165.0
lines = ["# Trap audit\n", "Generated by `python src/audit_traps.py`. Each section answers one row of the handbook's trap table.\n"]


def say(s=""):
    print(s)
    lines.append(s)


def trap1_leakage():
    say("## Trap 1: Future leakage\n")
    say("**Handbook check:** print train and validation date ranges and feature timestamps; use chronological or walk-forward validation.\n")
    cv = pd.read_csv(ROOT / "outputs" / "walk_forward_predictions.csv", parse_dates=["cutoff", "target_date"])
    daily, weather = load_daily(), load_weather()
    rows = build_rows(daily, weather)
    say("| Fold origin | Train target dates | Train rows | Validation target dates | Val rows | Gap OK |")
    say("|---|---|---|---|---|---|")
    for c, g in cv.groupby("cutoff"):
        tr = rows[(rows.target_date <= c) & rows.y.notna()]
        ok = tr.target_date.max() <= c < g.target_date.min()
        say(f"| {c.date()} | {tr.target_date.min().date()} .. {tr.target_date.max().date()} | {len(tr)} | "
            f"{g.target_date.min().date()} .. {g.target_date.max().date()} | {len(g)} | {'yes' if ok else '**NO**'} |")
    say("")
    # Feature timestamps: for each feature, the latest reading date it reads, relative to the origin.
    say("**Feature timestamps:** the latest data each feature reads, relative to origin day t (0 = the origin day itself, never later):\n")
    stamp = {**{f"lag{k}": f"t-{k}" if k else "t" for k in range(7)},
             "mean3": "t-2..t", "mean7": "t-6..t", "mean14": "t-13..t", "std7": "t-6..t", "max7": "t-6..t",
             "min7": "t-6..t", "trend7": "t-13..t", "sensor_level": "start..t", "sensor_offset": "start..t",
             "city_lag0": "t (all sensors)", "city_mean7": "t-6..t (all sensors)", "spike_rate30": "t-43..t",
             "h": "horizon (constant)", **{f"w0_{c}": "t" for c in ("temp_c", "humidity_pct", "wind_kmh")},
             **{f: "calendar of target date (known in advance)" for f in CALENDAR_FEATURES}}
    feats = PAST_FEATURES + CALENDAR_FEATURES + SPIKE_FEATURES
    assert set(stamp) == set(feats), set(feats) ^ set(stamp)
    say("| Feature | Reads |")
    say("|---|---|")
    for f in feats:
        say(f"| `{f}` | {stamp[f]} |")
    # Empirical proof on the real data: lag0 at origin t equals the reading dated t.
    o = rows[rows.origin == rows.origin.max()].iloc[0]
    rd = daily[(daily.sensor_id == o.sensor_id) & (daily.date == o.origin)].pm25.iloc[0]
    say(f"\nSpot check: sensor {o.sensor_id}, origin {o.origin.date()}: lag0 = {o.lag0:.1f} = reading dated "
        f"{o.origin.date()} ({rd:.1f}). The target is {o.target_date.date()} (h={o.h}).")
    say("Automated proof: `python tests/test_leakage.py` randomises all data after each origin and checks that every feature is identical.\n")


def trap2_networks(daily):
    say("## Trap 2: Networks mismatch\n")
    say("**Handbook check:** use the supplied conversions before aggregation; plot two same-area sensors after conversion.\n")
    say("Each area is measured by both networks (batch_1: UTC, PM2.5; batch_2: PKT, AQI), so the same-area comparison is batch_1 vs batch_2 for one sensor.\n")
    raw1 = pd.read_csv(ROOT / "sensors" / "batch_1_sensor_data.csv")
    raw2 = pd.read_csv(ROOT / "sensors" / "batch_2_sensor_data.csv")
    sid = "S01"
    r1 = raw1[raw1.sensor_id == sid].replace(-999, np.nan)
    r2 = raw2[raw2.sensor_id == sid].replace(-999, np.nan)
    r1_naive = pd.to_datetime(r1.timestamp).dt.normalize()  # UTC date, no shift
    d = daily[daily.sensor_id == sid]

    fig, ax = plt.subplots(2, 1, figsize=(12, 7), sharex=True)
    win = (d.date >= "2026-09-01") & (d.date <= "2026-09-30")
    m1 = (r1_naive >= "2026-09-01") & (r1_naive <= "2026-09-30")
    m2 = pd.to_datetime(r2.timestamp).between("2026-09-01", "2026-09-30")
    ax[0].plot(r1_naive[m1], r1.reading_value[m1], "o-", label="batch_1 raw (PM2.5, UTC date)")
    ax[0].plot(pd.to_datetime(r2.timestamp)[m2], r2.reading_value[m2], "s-", label="batch_2 raw (AQI, PKT date)")
    ax[0].set_title(f"{sid} Gulberg BEFORE conversion: different units and dates shifted by one day")
    ax[0].legend()
    ax[0].set_ylabel("raw value")
    ax[1].plot(d.date[win], d.pm25_b1[win], "o-", label="batch_1 PM2.5, shifted to PKT")
    ax[1].plot(d.date[win], d.pm25_b2[win], "x--", label="batch_2 AQI converted to PM2.5 (pre-2024 EPA)")
    ax[1].axhline(HAZ, color="red", lw=0.8, ls=":", label="hazardous 165")
    ax[1].set_title(f"{sid} AFTER conversion: the two networks overlap")
    ax[1].legend()
    ax[1].set_ylabel("PM2.5 µg/m³")
    ax[1].xaxis.set_major_formatter(mdates.DateFormatter("%b %d"))
    fig.tight_layout()
    fig.savefig(FIG / "trap2_networks_before_after.png", dpi=110)
    plt.close(fig)

    both = d.pm25_b1.notna() & d.pm25_b2.notna()
    all_both = daily.pm25_b1.notna() & daily.pm25_b2.notna()
    diff = (daily.pm25_b1 - daily.pm25_b2)[all_both]
    naive = pd.DataFrame({"sensor_id": raw1.sensor_id, "date": pd.to_datetime(raw1.timestamp).dt.normalize(),
                          "v": raw1.reading_value.replace(-999, np.nan)})
    nm = naive.merge(daily[["sensor_id", "date", "pm25_b2"]], on=["sensor_id", "date"])
    naive_diff = (nm.v - nm.pm25_b2).abs().median()
    say("| Check | Result |")
    say("|---|---|")
    say(f"| Median abs. difference, batch_1 vs converted batch_2, correct PKT alignment (all sensors) | **{diff.abs().median():.2f} µg/m³** |")
    say(f"| Same, if UTC dates are used without the +5 h shift | {naive_diff:.1f} µg/m³ (wrong day matched) |")
    say(f"| Correlation of the two networks after conversion ({sid}) | {d.pm25_b1[both].corr(d.pm25_b2[both]):.4f} |")
    say(f"| AQI table | pre-2024 US EPA (1714/1744 exact; 2024 table: 171/1744) |")
    say("\n![networks](figures/trap2_networks_before_after.png)\n")


def trap3_broken(daily):
    say("## Trap 3: Broken values\n")
    say("**Handbook check:** replace the sentinel before calculations, plot sensors, and flag, exclude or impute the faulty interval consistently.\n")
    raw1 = pd.read_csv(ROOT / "sensors" / "batch_1_sensor_data.csv")
    raw2 = pd.read_csv(ROOT / "sensors" / "batch_2_sensor_data.csv")
    raw_mean = raw1.reading_value.mean()
    say("| Check | Result |")
    say("|---|---|")
    say(f"| -999 in batch_1 / batch_2 | {(raw1.reading_value == -999).sum()} / {(raw2.reading_value == -999).sum()} |")
    say(f"| batch_1 mean if -999 were left in | {raw_mean:.1f} µg/m³ (vs {raw1.reading_value.replace(-999, np.nan).mean():.1f} correct) |")
    say(f"| -999 left after cleaning | {int((daily.pm25 == -999).sum())} |")
    say(f"| Gaps recovered from the other network | {int((daily.pm25_source == 'batch_2_aqi_inverted').sum())} |")
    st = daily[daily.stuck]
    stuck_id = st.sensor_id.iloc[0] if len(st) else daily.sensor_id.iloc[0]
    say(f"| Stuck interval | {stuck_id} {st.date.min().date()}..{st.date.max().date()}, value {st.pm25_b1.iloc[0]} in batch_1 "
        f"and AQI {st.aqi_b2.iloc[0]:.0f} in batch_2 |" if len(st) else "| Stuck interval | none detected |")
    say("| Handling | Excluded as training targets; features forward-fill from the last good day (max 3 days); same rule in every fold and in the final model |")

    # Coverage / quality heatmap: one cell per sensor-day, coloured by source.
    codes = {"batch_1": 0, "batch_2_aqi_inverted": 1, "stuck_excluded": 2, "missing": 3}
    grid = daily.assign(c=daily.pm25_source.map(codes)).pivot(index="sensor_id", columns="date", values="c")
    fig, ax = plt.subplots(figsize=(13, 4))
    cmap = matplotlib.colors.ListedColormap(["#d9e6f2", "#f4a261", "#d62828", "#000000"])
    ax.imshow(grid.to_numpy(), aspect="auto", cmap=cmap, vmin=0, vmax=3, interpolation="nearest")
    ax.set_yticks(range(len(grid)), grid.index)
    ticks = list(range(0, grid.shape[1], 14))
    ax.set_xticks(ticks, [grid.columns[i].strftime("%b %d") for i in ticks])
    ax.set_title("Data quality per sensor-day: blue = batch_1 PM2.5, orange = -999 filled from batch_2, red = stuck (excluded)")
    fig.tight_layout()
    fig.savefig(FIG / "trap3_coverage_heatmap.png", dpi=110)
    plt.close(fig)

    s = daily[daily.sensor_id == stuck_id]
    r = raw1[raw1.sensor_id == stuck_id]
    fig, ax = plt.subplots(figsize=(12, 4))
    rt = pd.to_datetime(r.timestamp) + pd.Timedelta(hours=5)
    ax.plot(rt.dt.normalize(), r.reading_value, color="#bbbbbb", lw=1, label="batch_1 raw (with -999)")
    ax.plot(s.date, s.pm25, "o-", ms=3, label="cleaned PM2.5")
    if len(st):
        ax.axvspan(st.date.min() - pd.Timedelta(hours=12), st.date.max() + pd.Timedelta(hours=12), color="red",
                   alpha=0.2, label=f"stuck {st.pm25_b1.iloc[0]} x{len(st)} (excluded)")
    ax.set_ylim(-50, 300)
    ax.set_title(f"{stuck_id} {s.area.iloc[0]}: raw readings vs cleaned series (any -999 dips are off-scale)")
    ax.legend(loc="upper left")
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %d"))
    fig.tight_layout()
    fig.savefig(FIG / "trap3_stuck_sensor.png", dpi=110)
    plt.close(fig)

    fig, axes = plt.subplots(5, 3, figsize=(14, 11), sharex=True, sharey=True)
    for ax, (sid, g) in zip(axes.flat, daily.groupby("sensor_id")):
        ax.plot(g.date, g.pm25, lw=0.9)
        ax.axhline(HAZ, color="red", lw=0.7, ls=":")
        ax.set_title(f"{sid} {g.area.iloc[0]}", fontsize=9)
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%b"))
    fig.suptitle("All 15 sensors after cleaning (red = hazardous 165)")
    fig.tight_layout()
    fig.savefig(FIG / "trap3_all_sensors.png", dpi=100)
    plt.close(fig)
    say("\n![coverage](figures/trap3_coverage_heatmap.png)\n![stuck](figures/trap3_stuck_sensor.png)\n![sensors](figures/trap3_all_sensors.png)\n")


def trap4_accuracy():
    say("## Trap 4: Misleading accuracy\n")
    say("**Handbook check:** evaluate hazardous recall plus precision and false alarms, not overall accuracy alone.\n")
    cv = pd.read_csv(ROOT / "outputs" / "walk_forward_predictions.csv")
    sub = pd.read_csv(ROOT / "predictions.csv")
    log = (ROOT / "outputs" / "log_final.txt").read_text(encoding="utf-8", errors="ignore")
    model = log.split("chosen model: ")[1].split(" ")[0]
    alarm = float(log.split("alarm at predicted >= ")[1].split(":")[0])
    y = cv.y >= HAZ
    say(f"Submitted model: **{model}**, alarm when predicted >= **{alarm:g}**. Validation = all 6 walk-forward folds ({len(cv)} rows, {int(y.sum())} hazardous).\n")
    say("| Alarm when predicted ≥ | Accuracy | Recall | Precision | Caught | False alarms | Missed |")
    say("|---|---|---|---|---|---|---|")
    for t in sorted({165.0, 150.0, 145.0, 140.0, alarm}, reverse=True):
        p = cv[model] >= t
        tp, fp, fn = int((p & y).sum()), int((p & ~y).sum()), int((~p & y).sum())
        acc = (p == y).mean()
        mark = " **(submitted)**" if t == alarm else ""
        say(f"| {t:g}{mark} | {acc:.1%} | {tp / max(tp + fn, 1):.2f} | {tp / (tp + fp) if tp + fp else float('nan'):.2f} | {tp} | {fp} | {fn} |")
    say(f"| *never alarm* | {(~y).mean():.1%} | 0.00 | n/a | 0 | 0 | {int(y.sum())} |")
    say("\nAccuracy is ~97% for every row, including \"never alarm\". It cannot tell the options apart, which is the trap. Recall, precision and false alarms can.")
    say(f"\nHoldout: {int(sub.hazardous.sum())} of {len(sub)} rows flagged hazardous; forecasts {sub.predicted_pm25.min():.1f}..{sub.predicted_pm25.max():.1f} µg/m³.")
    say("Trade-off and decision: SPRINT1.md section 6.\n")


def main():
    FIG.mkdir(parents=True, exist_ok=True)
    daily = clean.build_daily()
    trap1_leakage()
    trap2_networks(daily)
    trap3_broken(daily)
    trap4_accuracy()
    (ROOT / "outputs" / "trap_audit.md").write_text("\n".join(lines), encoding="utf-8")
    print("\nwrote outputs/trap_audit.md and outputs/figures/")


if __name__ == "__main__":
    main()
